// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_RXlepnoNEQmJFS01pNTGrwvRLe8KYw',
    appId: '1:873434983241:web:27e894814d630c95b88898',
    messagingSenderId: '873434983241',
    projectId: 'ecode-verifier',
    authDomain: 'ecode-verifier.firebaseapp.com',
    storageBucket: 'ecode-verifier.appspot.com',
    measurementId: 'G-NLRN3K623X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjf2WDsTciFjGyp6ENGsg2NiKZFsf6klY',
    appId: '1:873434983241:android:9746f66c70f49711b88898',
    messagingSenderId: '873434983241',
    projectId: 'ecode-verifier',
    storageBucket: 'ecode-verifier.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVtkRBq_iYwKK0wb4BEkT8heNqkZANGhc',
    appId: '1:873434983241:ios:01827f1b0d08e0afb88898',
    messagingSenderId: '873434983241',
    projectId: 'ecode-verifier',
    storageBucket: 'ecode-verifier.appspot.com',
    iosBundleId: 'com.example.ecodeVerrifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVtkRBq_iYwKK0wb4BEkT8heNqkZANGhc',
    appId: '1:873434983241:ios:de5c2a4cc9c24503b88898',
    messagingSenderId: '873434983241',
    projectId: 'ecode-verifier',
    storageBucket: 'ecode-verifier.appspot.com',
    iosBundleId: 'com.example.ecodeVerrifier.RunnerTests',
  );
}
